package: pwa
version: "0.0.2"
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/demo_addon

page:
  title: "PWA"
  icon: rex-icon fa-mobile
  perm: admin

  subpages:
    config:
      title: 'Einstellungen'
      icon: rex-icon fa-wrench
      subpages:
        manifest: { title: "manifest.json" }
        serviceworker: { title: "service-worker.js"}
    help:
      title: "Info"
      icon: rex-icon fa-info
      perm: pwa[]
      subpages:
        readme: { title: "README", subPath: "README.md" }
        changelog: { title: "CHANGELOG", subPath: "CHANGELOG.md" }

requires:
  redaxo: "^5.10"
installer_ignore:
  - node_modules
  - .env